### ISSUE TITLE
[Bug Maybe?] Schema parameter with differente definition in Windows and Samba

### ISSUE THREAD

**Issue by albertodlc** [smblds/smblds-container#14]
So I am using the docker image to mount an AD Test environment (the one in Production uses Windows AD). I have integrated the WebApp with this container correctly (the main problem I have is with the PWD update, etc because we are using Powershell to update the Production server passwords, but it is unrelated to this bug).

In the schema there is a param `pwdLastSet`. This param in the Windows Environment is defined as a long (ie. 13887887741848) but in this container it only allow to set 0 or -1.

Is there a way of updating that param or the schema or the image to use a data type like the one in Windows?

**Comment by albertodlc** [comment]
A little bit more of detail

*Windows*
![image](https://github.com/user-attachments/assets/4173a6bd-22ba-4e09-a606-53b2c22ce814)

*Container Image (Samba)*
![image](https://github.com/user-attachments/assets/a73d3fde-6841-4a70-8f98-9803972a37c4)

**Comment by robert-scheck** [comment]
https://learn.microsoft.com/en-us/windows/win32/adschema/a-pwdlastset should be the official description from Microsoft for `pwdLastSet`. If the behaviour of Samba AD in this container doesn't match with Microsoft  AD, it might be an issue in Samba 4. Setting `pwdLastSet` to `-1` should set it to the current timestamp (at least that's my understanding), but according to https://lists.samba.org/archive/samba-technical/2013-February/090521.html this didn't work at least at some time in history (maybe that behaviour still applies).

**Comment by albertodlc** [comment]
Thank you!! For the quick response and the links. I double checked the records I was loading in my .ldif, and I was trying to set directly the exported timestamp from Production. Just changing that value to -1 and rebuilding the container set the field correctly.

**Comment by robert-scheck** [comment]
You're welcome. Great to read that it helped you!
