### ISSUE TITLE
Hello!tihs is not bug ,How to use smblds with Docker on NAS?(你好这不是bug，怎么在nas上的docker使用smblds）

### ISSUE THREAD

**Issue by JyenZhou** [smblds/smblds-container#3]
I'm trying to use the Docker image (https://hub.docker.com/r/smblds/smblds) on my NAS, but there are many configurations to be made, and I couldn't find the default ports 455, 137, 139. As a beginner, how should I proceed? I'm mostly concerned about the port mapping, shared directories, and the startup command that doesn't require admin privileges. In fact, you don't need to worry about the NAS itself, as the important parameters to consider are the port mapping, shared directories, and non-admin startup command.
Can the documentation be more detailed? The parameters shown in the image below are required by default, but I have no idea what they mean, so I don't even know where to map the main directory.
![image](https://user-images.githubusercontent.com/37990159/233817054-1f33ca43-904c-48fc-a92d-17523a87604d.png)
![image](https://user-images.githubusercontent.com/37990159/233817064-302c51d3-4909-45ff-942f-7e3f685014c9.png)
我在nas上使用docker 镜像（https://hub.docker.com/r/smblds/smblds） 
 发现要配置的东西比较多，甚至默认的端口455，137,139都没看到。我是个小白应当如何使用，实际上你不需要关注nas，nas上比较关心的参数是要映射的端口号，要共享的目录，以及不涉及管理员权限的启动命令。
 说明文档能够更详细点吗，我下面图片上的参数是默认出来必填的，我根本不知道他的意思，所以连映射主目录在哪都不知道

**Comment by robert-scheck** [comment]
I am sorry, but the smblds-container can _not_ be used as a Samba file share. And this is why ports 445 and 137-139 are missing. The smblds-container exists for use-cases where _only_ the LDAP component is needed (that means ports 389, 636, 3268 and/or 3269). So, if you would like to use the ports 445 and/or 137-139, I am afraid you have to search for a suitable Samba container with file sharing support.
