### ISSUE TITLE
Loading test data - any adivice?

### ISSUE THREAD

**Issue by dolzenko** [smblds/smblds-container#4]
First of all - big thank you for this, very useful. Now to my question: I'm using this in test environment and assuming I want to load this with some data - how can I do this? One way is a bash script with `samba-tool user add ...` commands, works fine, until you need to use the SIDs which will differ on every container run (possibly). Is there any other solution I'm missing? Is it possible to add some parameter which will make SIDs generated by Samba stable/predictable?

**Comment by robert-scheck** [comment]
First of all, thank you for using this container and for asking! The easiest way I could think of is putting `/var/lib/samba/` on persistent storage, but that may or may not be suitable for your exact scenario. If you could go into details about your overall scenario, I'm happy to spend more thoughts and/or to add what's missing (if feasible).

By the way, running e.g. `ldbedit -H /var/lib/samba/private/sam.ldb.d/DC=SAMDOM,DC=EXAMPLE,DC=COM.ldb -e 'sed -i "s/<old SID>/<new SID>/g"' '(sAMAccountName=Administrator)'` could also be a way to change SIDs, but I didn't dig into this deeply myself, yet.

**Comment by dolzenko** [comment]
@robert-scheck big thank you for the advice (and for the the project again). My scenario is as follows - I have a big enterprisey Ruby on Rails app which integrates with LDAP for authentication and managing access rules. The app has a test suite (predictably written in Ruby :) ). Now to write the tests for the LDAP logic it would be great to have the data loaded into LDAP from Ruby. It would make the test logic clear and simple to review, e.g. I will have

```ruby
user = create(:ldap_user, name: 'User') # this creates user in Samba
group = create(:ldap_group, name: 'Group', users: [user]) # this creates group and associates user with it

create(:group_permission, group: group.sid, access_level: :admin) # this is an in-app object I setup specifically for this test and which uses SIDs to reference LDAP groups

# then I test if user can login and receives admin rights
```

So I thought about having Bash script with some `samba-tool` invocations (here your SID trick might work well), but again - having the database in LDIF (or JSON) format to be loaded on the test run would be much cleaner I think. So I guess my problem boils down to finding a clear and concise way to store and load Active Directory/LDAP test fixtures.

**Comment by dolzenko** [comment]
I think I understood your play finally - you expect your users to create their own images with customization scripts placed in /entrypoint.d/, so currently I have

```
FROM smblds/smblds:latest

COPY seed.sh /entrypoint.d/
```

and in seed.sh something like

```
samba-tool ou add OU=TestOU
samba-tool user add testuser pw
```

which so far looks very **awesome**, I think this can be closed now :)

**Comment by robert-scheck** [comment]
> I think I understood your play finally - you expect your users to create their own images with customization scripts placed in /entrypoint.d/, […]

No, I'm _not_ expecting users to create their own images, the entrypoint can be leveraged even more simply by mounting your customization scripts directly into `/entrypoint.d/`, e.g. `docker run -v ./seed.sh:/entrypoint.d/my-seed.sh […]`.

**Comment by dolzenko** [comment]
Even more amazing, thanks!

**Comment by robert-scheck** [comment]
I noticed I didn't document the mointpoints outside of the `Dockerfile`. I'll do that next and also mention `/entrypoint.d/` with an example there. Thank you for implicitly pointing out this missing piece.
